### PR TITLE
Update repo, remove extraneous files

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

Should not be merged until https://github.com/freeCodeCamp/freeCodeCamp/pull/40218 hits production.

### CODE REVIEW

**Review by RandellDawson — CHANGES_REQUESTED** [review]
@nhcarrigan Let's delete the `/tests/1_unit-tests.js` from the boilerplate repo.

Would also like to see the following removed from `/routes/api.js`

```js
/*
*
*
*       Complete the API routing below
*
*
*/
```

and the following from the `/test/2_functional-tests.js` file:
```js
/*
*
*
*       FILL IN EACH FUNCTIONAL TEST BELOW COMPLETELY
*       -----[Keep the tests in the same order!]-----
*       (if additional are added, keep them at the very end!)
*/
```
If you go with something like was done boilerplate in  be changes to explain what test to write like is done in boilerplate PR https://github.com/freeCodeCamp/boilerplate-mochachai/pull/27, then you can modify the `/learn` page like https://github.com/freeCodeCamp/freeCodeCamp/pull/39976 referencing the test by a commented number (i.e. `// #1`).

**Comment by naomi-lgbt** [comment]
Just for some additional clarification:

The mocha-chai boilerplate referenced adds `assert.fail` statements to the tests. That's relevant, there, because it's a lesson boilerplate vs. a project boilerplate - for the project, it should just be the `test("string), function(done) {})` right? Like so:

```js
suite('Functional Tests', function() {
    
    suite('GET /api/stock-prices => stockData object', function() {
      
      test('1 stock', function(done) {

      });
      
      test('1 stock with like', function(done) {
        
      });
      
      test('1 stock with like again (ensure likes are not double counted)', function(done) {
        
      });
      
      test('2 stocks', function(done) {
        
      });
      
      test('2 stocks with like', function(done) {
        
      });
      
    });
});
```

**Review by moT01 — COMMENTED** [review]
I looked over the PR's for this project - for the most part, I think they look good - I did have a couple potential issues with this boilerplate.

- dotenv is required in `server.js`, but the package isn't added to `package.json`, so when you try to run the boilerplate, you get an error - perhaps we should include that package with the boilerplate?

- I also tried to run `npm ci` and got ``"can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing."`` This one isn't a big deal, but I'm wondering if we should update the package-lock or perhaps just remove it. I would be fine leaving it how it is as well, I don't think it will cause problems.

**Comment by naomi-lgbt** [comment]
Sure, I can take care of these later this afternoon. 🙂

**Comment by RandellDawson** [comment]
>   This one isn't a big deal, but I'm wondering if we should update the package-lock or perhaps just remove it. I would be fine leaving it how it is as well, I don't think it will cause problems.

I would prefer the two files are in sync.

**Comment by naomi-lgbt** [comment]
Added `dotenv` as a dependency and regenerated the `package-lock.json`.

**Comment by RandellDawson** [comment]
@nhcarrigan To bring the boilerplate up-to-date with the changes on and, can you change line 25 of the `views/index.html` from:
```
      <code>{"stockData":[{"stock":"MSFT","price":"62.30","rel_likes":-1},{"stock":"GOOG","price":"786.90","rel_likes":1}]}</code>
```
to:
```
      <code>{"stockData":[{"stock":"MSFT","price":"62.30","rel_likes":-1},{"stock":"GOOG","price":786.90,"rel_likes":1}]}</code>
```

**Comment by naomi-lgbt** [comment]
@RandellDawson done 🙂

**Review by RandellDawson — APPROVED** [review]
Everything looks good to me now.  @moT01 I think it is safe to go ahead and merge this one.

**Comment by moT01** [comment]
Shouldn't we wait on this until the other PR hits production?

Edit: yea, I think we should since the functional test file won't have the instructions when this is merged, so they will need to get those from the /learn page

**Comment by naomi-lgbt** [comment]
Yes - there are changes here that rely on the information I added to the learn page.

If needed, I can separate the example output change into a separate PR so it can be merged sooner.

**Comment by moT01** [comment]
I would just leave this - it's ready to go. No real rush to get it out, it will probably only be a few days.

**Pull request merged**
