### PR TITLE
removed unneeded jQuery and added action url to html forms. forms now submit to correct url

### PR DESCRIPTION
**Pull request by sophyphreak**
When doing this challenge, I realized during testing that the form didn't work with the specifications given in the project challenge description. The jQuery has some problem in it, so I decided to go to pure HTML GET forms like some of the other projects use. The GET request now occurs correctly using /api/stock-prices as its endpoint.

### CODE REVIEW

**Comment by sophyphreak** [comment]
Hey, so, just wanted to check in. This seemed pretty urgent to me when I fixed it, so I'm pretty surprised this pull request hasn't been accepted. I understand everyone is busy, but the front end boilerplate is totally broken right now.

**Comment by sophyphreak** [comment]
Ok, re: [my post in the main freeCodeCamp repo](https://github.com/freeCodeCamp/freeCodeCamp/issues/35924).

This pull request and my other one [here](https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/3) fix bugs in the boilerplate that render the front end of the application non-functional. This looks **extremely unprofessional** for any potential employer that might look at this project in your portfolio. 

I fixed this breaking bug in my portfolio, and I want to fix it in everyone's.

I considered this a pretty urgent pull request back in February, and I consider it no less urgent now.

**Comment by RandellDawson** [comment]
@sophyphreak Do you have a link to your working project?  I want to test something.

**Comment by sophyphreak** [comment]
@RandellDawson Yeah sure, no worries. [Here is the github code](https://github.com/sophyphreak/stock-price-checker), and [here is the demo](https://stock-price-checker.andrew-horn-portfolio.life/).

**Comment by sophyphreak** [comment]
Hey @RandellDawson, 

I really appreciate you looking at accepting my pull request. As you know, I think this is a really important thing that should be fixed for all freeCodeCampers as soon as possible so their portfolios look professional for prospective employers. 

Were you able to test the part of my working project that you were looking to test?

Thanks,
Sophyphreak

**Comment by ganeshh123** [comment]
Thanks for fixing the broken frontend :)

**Comment by RandellDawson** [comment]
@Sky020 I think we can close this one.

**Comment by ShaunSHamilton** [comment]
@RandellDawson I would actually be for changes like this. However, there are a few issues here:
1) The proposed change does not allow for the response to be sent to the `#jsonResult` (`code`) element
2) The proposed change causes the page to refresh. It would be preferable to prevent this

So, provided that is resolved, we can move forward with this 👍

**Comment by naomi-lgbt** [comment]
Hey there @sophyphreak,

Just checking in - have you had a chance to review the recommendations that Shaun provided?

**Comment by RandellDawson** [comment]
Hi @sophyphreak,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

**Comment by sophyphreak** [comment]
Not a problem. I don't think I have time to make the requested changes. Take care!

**Pull request closed without merging**
